### ISSUE TITLE
Start bits wrong

### ISSUE THREAD

**Issue by ghost** [pschwager/waterkotte#1]
Hallo,

ich habe hier dein waterkotte.c gefunden und das Ganze kompiliert. 
Leider bekomme ich hier folgende Fehlermeldung:

start bits wrong!
 ff 10 02 00 17 1f be 08 08 05 03 05 1f c6 61 cb bf 99 6c 12 40 34 4f eb bf 1a be d9 41 7c e1 d5 41 02 8e 02 42 04 00 58 42 72 9c 59 42 52 38 de c2 00 00 70 41 17 55 9c 40 b0 7d 32 3f e0 4c a4 bf b6 4b f9 41 5b 6b ed 40 00 00 00 00 3f ca 55 40 01 ca 4b 41 1a be d9 41 7c e1 d5 41 fe ff a7 41 7c e1 d5 41 72 9c 59 42 1c 14 09 1c 02 17 ec 68 cc 46 6f f2 8c 46 d7 d8 fe 45 55 9a 45 43 00 2d 0e 18 0a 05 07 2d 0e 18 0a 05 00 00 00 00 00 50 4e 00 00 02 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 28 f3 02 00 02 a3 20 00 16 00 00 00 02 00 00 00 00 00 00 01 ce 01 08 08 00 00 00 00 00 00 00 01 2a 00 2b 01 2a 00 28 35 9c 00 ed ff 83 41 06 00 b8 41 fc ff b7 41 00 00 20 42 00 5a 66 be 41 00 fe ff 3f c0 00 00 00 00 00 18 00 00 16 00 00 04 00 00 20 42 00 00 00 40 02 01 f3 ff af 41 fe ff a7 41 00 00 c8 41 01 00 94 41 00 00 05 06 00 00 17 04 00 58 42 00 00 d0 41 00 00 a0 40 00 00 00 3f 00 00 00 03 05 1f 00 10 03 20 38 ff

Ich betreibe eine Resümat CD4 8126. Sollte das damit laufen ? Gäbe es eine Möglichkeit das simple anzupassen.

Vielen Dank
Gruß

**Comment by pschwager** [comment]
Hallo,

vom Protokoll her sollte die Antwort mit einem 10 02 00 17 anfangen. 

Eine etwas genauere Beschreibung des Protokolls kannst du hier finden:
https://github.com/mwllgr/fhem-waterkotte-resuemat-cd4/blob/master/README.md

Ich würde darauf tippen, dass deine Version ein paar Werte weniger kennt und somit die Response kleiner sein wird. Um weniger Daten abzufragen, kannst du diese Zeile entsprechend anpassen:
https://github.com/pschwager/waterkotte/blob/main/waterkotte.c#L71

Ansonsten nochmal prüfen ob du eine kleine Baudrate nutzen musst
https://github.com/pschwager/waterkotte/blob/main/waterkotte.c#L36-L37
